-- ============================================================================
-- Seed: the NorCal SCI mentor directory
-- ============================================================================
-- 23 members, seeded so the Peers deck demonstrates anything at all — an empty
-- deck hides every layout, filter and empty-state bug there is.
--
-- ---------------------------------------------------------------------------
-- Where this data comes from
-- ---------------------------------------------------------------------------
-- NorCal SCI's peer mentor directory, used with their permission. These are
-- real people. That fact governs everything below:
--
--   * Nothing is invented. Where the directory is silent, the column is null.
--     Injury dates in particular are absent from the source and are NOT
--     synthesized — a plausible-looking date we made up would be
--     indistinguishable from one the person gave us, and every screen that
--     reads it would be asserting a medical fact about somebody on our say-so.
--   * Phone numbers are reserved 555 placeholders. The directory carries no
--     numbers; the column is not null only because it is sign-in identity for
--     real members.
--   * Birth dates are 1 January of the year implied by the age the directory
--     gives. That reproduces the age exactly and claims nothing more.
--   * Gender is null throughout. The source carries an undocumented flag on six
--     entries which is read nowhere; no gender is inferred from it.
--
-- ---------------------------------------------------------------------------
-- Mentors
-- ---------------------------------------------------------------------------
-- Every person in this directory is in fact a NorCal SCI peer mentor. Five are
-- marked `mentor` here and the rest `peer`, so both sides of the Peers deck
-- have somebody in them. The five were drawn with a fixed seed, so the pick is
-- reproducible rather than different on every regeneration.
--
-- ---------------------------------------------------------------------------
-- Ids, and re-running
-- ---------------------------------------------------------------------------
-- Each id is derived from the person's name, so the same person always becomes
-- the same row. With `on conflict (id) do nothing` this migration is a no-op
-- against a database that already has it.
--
-- These ids belong to no auth account, so every policy on `members`
-- (`auth.uid() = id`) rejects writes to them from every caller: readable
-- through browse_members, writable by nobody.
--
-- `is_seed` marks them. If one of these people later joins for real, that flag
-- is how their own row gets reconciled with this one instead of sitting beside
-- it as a duplicate.
--
-- ---------------------------------------------------------------------------
-- Photos
-- ---------------------------------------------------------------------------
-- `photo_url` still points at NorCal SCI's own CDN. A later step copies these
-- into our `photos` bucket and rewrites the column: an app should not depend on
-- another organization's bandwidth or URL structure staying put.
-- ============================================================================

insert into public.members (
  id,
  type,
  display_name,
  phone,
  birth_date,
  level_range,
  exact_level,
  completeness,
  injury_date,
  injury_date_precision,
  city,
  state,
  photo_url,
  bio,
  gender,
  languages,
  independence,
  employment,
  field_of_work,
  education,
  marital_status,
  has_children,
  interests,
  topics,
  self_care,
  affiliations,
  wants_to_mentor,
  is_seed
) values
  ('c85c10bf-0226-394f-8c91-2a2ffc40a147', 'peer', 'Ajay', '15555550000', '1996-01-01', 'C5–C8', 'C7', 'Incomplete', null, null, 'San Jose', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/76946e11-5bef-4527-999b-9691cf49e418/Ajay.jpg?format=500w', 'Manual chair. Strong upper body, weaker left tricep/lat/chest, impaired hand function (stronger grip right hand). Global spasticity used for hand function, transfers, and walking short distances with spotters. Lives alone.', null, array['English']::text[], 'Completely independent', 'Student', 'Nutrition (in grad school)', 'In progress — grad school for nutrition', null, null, array['Water sports', 'Fitness & exercise', 'Cooking']::text[], array['Adaptive sports', 'Back to school', 'Suprapubic catheter', 'UTIs', 'Getting into dating']::text[], array['Suprapubic catheter', 'Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('d49fe7d1-73df-41c5-50ef-29ce445b6bd9', 'peer', 'Bob', '15555550001', '1955-01-01', 'C5–C8', 'C6/7', 'Incomplete', null, null, 'Aptos', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/c472dc43-a8b2-48e6-a819-99a7046c8901/Bob+Spisak.jpg?format=500w', 'Manual chair. Lives alone independently. Volunteers for VMC, CASA, Ride-A-Wave, Day of Discovery and the Christopher Reeve Foundation.', null, array['English']::text[], 'Completely independent', 'Retired', 'Mechanic, truck driver, firefighter', 'Associate''s degree', null, true, array['Cycling', 'Volunteering', 'Car restoration']::text[], array['Adaptive equipment', 'Adaptive sports', 'Vehicles']::text[], array['Vehicle modifications', 'Wheelchair assist devices']::text[], array['NorCal SCI', 'Christopher Reeve Foundation']::text[], false, true),
  ('43bb63c6-939e-461e-264c-4b2a817beb91', 'peer', 'Dante', '15555550002', '1997-01-01', 'C1–C4', 'C4', 'Incomplete', null, null, 'Aptos', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/c1874d1d-6393-4625-9f20-eeb7ad0ee156/reevefoundationphoto.jpg?format=500w', 'No assistive devices; sometimes an AFO on the left leg. Good return of function in all four limbs. Lives at home with parents but is physically independent.', null, array['English']::text[], 'Completely independent', 'Full time', 'Freelance photographer (previously accounting)', 'BS Business Administration', null, null, array['Cycling', 'Photography', 'Mountain biking']::text[], array['Back to school', 'Being injured as a teen', 'Navigating walking again', 'Adaptive cycling']::text[], '{}', array['NorCal SCI']::text[], false, true),
  ('bc62c2b7-dc4f-3146-e5cf-c453023ad22f', 'peer', 'Debra', '15555550003', '1956-01-01', 'C1–C4', 'C4', 'Incomplete', null, null, 'San Jose', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/e23dac50-c3c1-4f5f-965d-ab5acd9f7593/unnamed+%282%29.jpg?format=500w', 'Mobility scooter. Brown-Séquard syndrome. Walks short distances with a walker. Volunteers with Medical Volunteers for Disaster Relief and presents on emergency preparedness for people with disabilities. Lives independently.', null, array['English']::text[], 'Completely independent', 'Retired', 'Nurse educator (Santa Clara County 911)', 'Master''s in Nursing Leadership', null, null, array['Travel', 'Water sports', 'Camping & outdoors']::text[], array['Emergency preparedness', 'Neural implant', 'Ileostomy']::text[], array['Ileostomy', 'Neural implant', 'Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('11712b50-bf2e-3c6b-f736-250e96e6987f', 'peer', 'Gretchen', '15555550004', '1991-01-01', 'C5–C8', 'C5/6', 'Incomplete', null, null, 'Clovis', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/fd970ac9-4ba3-478e-8879-b32440c372ea/Gretchen.JPG?format=500w', 'Manual chair with SmartDrive power assist. Can stand and use a walker short distances around the house. Lives with parents. Working with vocational rehab to find a full-time job.', null, array['English']::text[], 'Mostly independent', 'Seeking work', 'Medicine', 'Medical school graduate', null, null, array['Travel', 'Reading', 'Gardening']::text[], array['Advocacy', 'Travel', 'Neurogenic bladder and Botox', 'Mental health', 'Adaptive home improvements']::text[], array['Botox', 'Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('f2851f46-8fc1-ab8d-842c-33b7ceaccc9d', 'mentor', 'Jan', '15555550005', '1962-01-01', 'T7–T12', 'T12', 'Complete', null, null, 'Santa Cruz', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/e62b8066-8eb5-4a2b-b1d5-6baa220f7d10/Jan+Edwards.jpeg?format=500w', 'Mostly manual with SmartDrive. Shoulder surgeries and arthritis have led to some upper body weakness. Paralympian and marathon participant post-injury. Sits on the board of a camp for kids and adults with disabilities and holds a leadership role in Canine Companions. Retired, lives with her husband.', null, array['English']::text[], 'Completely independent', 'Retired', 'Accounting (CPA)', 'BA Accounting, CPA', 'Married or partnered', null, array['Water sports', 'Camping & outdoors', 'Individual sports']::text[], array['Athletics and adaptive sports equipment', 'Other adaptive equipment', 'Self and suprapubic cath', 'Pain management', 'Pregnancy with paraplegia', 'Medical write-offs']::text[], array['Suprapubic catheter', 'Intermittent catheterization', 'Wheelchair assist devices', 'Service animals']::text[], array['NorCal SCI', 'Canine Companions']::text[], true, true),
  ('d1ce8fad-f0c3-3b98-a006-9f19e6024067', 'peer', 'Jake', '15555550006', '1997-01-01', 'C5–C8', 'C6', 'Complete', null, null, 'Carlsbad', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/5742046e-62a9-4ad6-ad79-f534cf0ad4ba/IMG_3076.JPG?format=500w', 'Power-assist manual chair; a weak tricep is his lowest level of function.', null, array['English']::text[], 'Mostly independent', 'Full time', 'Quality engineer', 'Master''s in Biomedical Engineering', 'Married or partnered', null, array['Team sports', 'Camping & outdoors', 'Fitness & exercise']::text[], array['Adaptive equipment', 'Adaptive sports', 'Caregivers', 'Back to school and work', 'Advocacy', 'Intimacy', 'Bladder surgery']::text[], array['Hiring & managing caregivers', 'Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('2bae42ae-8699-c6ba-3cb2-81b345ee504a', 'peer', 'Joe', '15555550007', '1971-01-01', 'C5–C8', 'C6', 'Complete', null, null, 'Campbell', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/80db4a89-7bfa-4038-8f33-4c62116f9152/image0.jpg?format=500w', 'Manual chair with push assist. No triceps, but with a functioning tenodesis grip.', null, array['English', 'Spanish']::text[], 'Completely independent', 'Full time', 'Independent living center', 'M.A. degree', 'Married or partnered', null, array['Travel', 'Assistive tech', 'Film']::text[], array['Assistive technology', 'Living independently']::text[], array['Wheelchair assist devices', 'Dictation software']::text[], array['NorCal SCI']::text[], false, true),
  ('bd3974e7-625a-3bc1-cd45-91523eef6e3c', 'peer', 'Joseph', '15555550008', '1986-01-01', 'L1–S5', null, 'Do not know', null, null, 'Oakland', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/81206dc1-abd7-4cb4-aa41-2a76565d7535/Screenshot_20240408_152935_Instagram.jpg?format=500w', 'Motor scooter; weak leg strength. Lives independently.', null, array['English']::text[], 'Completely independent', 'Full time', 'Federal government', 'Chico State graduate', null, null, '{}', array['Mobility']::text[], array['Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('c5a7cc04-f040-60a7-7f18-5bdabd046ade', 'mentor', 'Kerry', '15555550009', '1991-01-01', 'T1–T6', 'T5', 'Complete', null, null, 'San Jose', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/f088fb4d-8a29-4ac4-8933-77ef67c90057/image0.jpeg?format=500w', 'Manual chair; no sensation or function from the chest down, full arm and hand function. Lives with a roommate in a two-bedroom apartment.', null, array['English']::text[], 'Completely independent', 'Full time', 'Orthopedic surgery practice', 'BS Athletic Training, Master''s Exercise Science', null, null, array['Team sports', 'Fitness & exercise', 'Travel']::text[], array['Adaptive sports', 'Living independently', 'Driving', 'Working full time']::text[], array['Vehicle modifications']::text[], array['NorCal SCI']::text[], true, true),
  ('83a2c92f-8099-caef-b987-bac63ef13bd4', 'peer', 'Kevin', '15555550010', '1962-01-01', 'C1–C4', 'C1', 'Incomplete', null, null, 'Fremont', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/e5e7b48d-3c55-4e07-8643-221d0a883b8a/KevinLee2023.png?format=500w', 'Mobility scooter, or forearm crutches for short distances. Moves slowly with limited strength and significant tone. Board treasurer at ReCARES and a weekly volunteer at SCVMC SCI Peer Support. Lives with his long-term partner.', null, array['English']::text[], 'Mostly independent', 'Not currently working', 'Computer networking and software test (pre-injury)', 'BS Computer Science', null, null, array['Arts & crafts', 'Woodturning', '3D printing']::text[], array['Most SCI topics, after 20 years attending and co-leading peer support groups']::text[], array['Wheelchair assist devices']::text[], array['NorCal SCI', 'ReCARES', 'SCVMC SCI Peer Support']::text[], false, true),
  ('717f39d4-5aae-0836-dcf5-9bdbc55cf3b2', 'peer', 'Yazmin', '15555550011', '1998-01-01', 'T7–T12', 'T11', 'Incomplete', null, null, 'Stockton', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/8f3e3166-7d97-408c-b1b0-a00f666e1f39/Yazmin+Duran+.JPG?format=500w', 'Has used manual wheelchairs, walkers and leg braces; uses a cane. Full hand and arm function. Thighs most affected, especially quadriceps; almost full function of lower legs and feet. Lives with family.', null, array['English', 'Spanish']::text[], 'Mostly independent', 'Student', 'Business (in training)', 'In college for a business degree', null, null, array['Reading', 'Writing & storytelling']::text[], array['Pain management', 'Going back to school']::text[], array['Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('0da2c170-5e86-315e-b3e1-a54b43b7a45a', 'mentor', 'Lake', '15555550012', '1973-01-01', 'T7–T12', 'T11', 'Complete', null, null, 'Santa Rosa', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/23df5b44-8ae0-49e2-b029-da80e79b07f1/Untitled+-+2024-05-16T113047.516.png?format=500w', 'Manual chair; full function above the belly button. Volunteer art teacher at a women''s treatment center and hosts an SCI online support group. Lives alone; daughter in college.', null, array['English']::text[], 'Completely independent', 'Full time', 'Construction company owner (previously disability resource center)', 'Some college', null, true, array['Painting', 'Gardening', 'Reading']::text[], array['Basketball', 'Advocacy', 'Pregnancy and motherhood', 'Business ownership', 'Travelling by air and vehicle']::text[], array['Vehicle modifications', 'Wheelchair assist devices']::text[], array['NorCal SCI']::text[], true, true),
  ('ec2d4f08-df45-2ea8-58fb-be791ef09ef2', 'peer', 'Lindsay', '15555550013', '1984-01-01', 'T1–T6', 'T4', 'Complete', null, null, 'Livermore', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/8514761c-5be4-41f4-9413-4c3ff8769fa8/LIndsay+Ulrey.jpeg?format=500w', 'Manual chair with SmartDrive and a Striker attachment; occasionally a power chair. Full function above the level of injury, limited below. Board member of the Wheel with Me Foundation and runs a support group for ''wheelie mamas''. Married, two kids, dog.', null, array['English']::text[], 'Completely independent', 'Full time', 'Clinical psychology (private practice)', 'Doctorate in clinical psychology', 'Married or partnered', true, array['Cycling', 'Camping & outdoors', 'Team sports']::text[], array['Adaptive biking gear', 'Being a mom in a wheelchair', 'Driving', 'Home adaptations', 'Cooking']::text[], array['Vehicle modifications', 'Wheelchair assist devices']::text[], array['NorCal SCI', 'Wheel with Me Foundation']::text[], false, true),
  ('4df177ee-e1f0-c47e-9e03-fe9473651a86', 'peer', 'Matt', '15555550014', '1987-01-01', 'T1–T6', 'T4', 'Complete', null, null, 'San Francisco', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/dc49f388-4545-43f2-a287-88e130637678/Leonard_headshot.jpg?format=500w', 'Manual chair. No motor or sensation below mid-chest; full strength and feeling above. Very independent; drives with hand controls. Lives alone, dog owner.', null, array['English']::text[], 'Completely independent', 'Full time', 'Freelance', 'BA Film; Master''s in wine studies', null, null, array['Water sports', 'Fishing', 'Ski & snowboard']::text[], array['Adaptive equipment', 'Most adaptive sports', 'Pain management']::text[], array['Vehicle modifications']::text[], array['NorCal SCI', 'Christopher Reeve Foundation', 'High Fives Foundation']::text[], false, true),
  ('de265880-f900-55e1-dd5a-4cd8b0df72c0', 'peer', 'Nicole', '15555550015', '1998-01-01', 'C5–C8', 'C6', 'Incomplete', null, null, 'Santa Clara', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/d1173043-7784-4c0f-8764-fd15165a7d3d/Nicole+Rosario.JPG?format=500w', 'Mostly manual chair; power chair to travel locally. Some hand and tricep function on the left, some tricep on the right. Lives alone with her dog.', null, array['English']::text[], 'Completely independent', 'Full time', 'Software engineering', 'Bachelor''s in Engineering', null, null, array['Team sports', 'Video games', 'Drones & robotics']::text[], array['Adaptive equipment', 'SmartDrive', 'Path to returning to driving', 'Wheelchair rugby', 'Back to work', 'Suprapubic tube', 'Independence']::text[], array['Suprapubic catheter', 'Vehicle modifications', 'Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('17c29016-7180-e835-4503-3f8898b06b8b', 'mentor', 'Robert', '15555550016', '1960-01-01', 'C1–C4', 'C3', 'Incomplete', null, null, null, 'ID', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/b3524000-a6e3-44e8-898e-b0bd735c2c27/20240524_075738.jpg?format=500w', 'High functioning; can walk but has issues, same with arms and hands. Spasticity, bowel and bladder issues. Very self-motivated to improve and to help others; made a strong recovery through his own work ethic. Lives with his wife.', null, array['English']::text[], 'Mostly independent', 'Not currently working', 'Underground construction', 'High school graduate', 'Married or partnered', null, array['Fitness & exercise', 'Drums', 'Cooking']::text[], array['Self-rehabilitation']::text[], '{}', array['NorCal SCI']::text[], true, true),
  ('ee7c2dfe-6203-df03-77f2-03e81a33bef0', 'peer', 'Scott', '15555550017', '1971-01-01', 'T7–T12', 'T8', 'Incomplete', null, null, 'Kerman', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/ebc79199-e414-4570-8a14-3feccf1c3977/Scott+Zulewski.jpeg?format=500w', 'Manual chair. Very little leg movement; can wiggle toes and flex the right quad. Hands and arms are normal. Lives with his wife, daughter and granddaughter.', null, array['English']::text[], 'Completely independent', 'Full time', 'Accounting (CPA)', 'College graduate, CPA', 'Married or partnered', true, array['Team sports', 'Piano']::text[], array['Working while dealing with SCI', 'Pain management']::text[], array['Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('5c81cd57-47f7-0096-c2fa-80dde9a8ce08', 'peer', 'Sean', '15555550018', '1984-01-01', 'C5–C8', 'C6/7', 'Complete', null, null, 'Fremont', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/d4a7315d-d3c1-42fc-8bb6-0b8d52ac3fbf/NorCalSCI+Photo+%281%29.jpg?format=500w', 'Manual chair, sometimes with power assist. Most tricep function, impaired hand function, no sensation or movement in torso or legs. Lives alone in an apartment.', null, array['English']::text[], 'Completely independent', 'Student', 'Culinary (pre-injury chef)', 'Culinary school; working on a BA in Psychology', null, null, array['Team sports', 'Cycling', 'Travel']::text[], array['Moving back in with family after injury', 'Moving out to live independently again', 'Romantic relationships', 'Adaptive sports and equipment', 'Driving adaptations', 'Applying for grants and government programs', 'Travel', 'Botox']::text[], array['Botox', 'Vehicle modifications', 'Wheelchair assist devices']::text[], array['NorCal SCI']::text[], false, true),
  ('4574f3e5-f615-d38a-80ba-2fef00000ade', 'peer', 'Tiffany', '15555550019', '1973-01-01', 'C5–C8', 'C5/6', 'Complete', null, null, 'Sacramento', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/7b8f8576-f344-4c67-a9de-3d1650d90039/Poland_Headshot+%281%29.JPG?format=500w', 'Power chair. Has a hospital bed and an alternating pressure relief mattress. Has biceps but no triceps; uses typing aids and Dragon at times to write with her voice. Runs and attends several peer support groups including a monthly women''s group on Zoom. Lives with her mother, who is her full-time caregiver.', null, array['English']::text[], 'Partially dependent', 'Student', 'Human services', 'AA Human Services; working toward a BA in Disability Studies', null, null, array['Performing arts', 'Concerts', 'Comedy']::text[], array['Going back to school', 'Returning to college', 'Canine Companions']::text[], array['Dictation software', 'Service animals', 'Wheelchair assist devices']::text[], array['NorCal SCI', 'Canine Companions']::text[], false, true),
  ('9e79bac7-c43a-05b0-930e-2402417bdbf5', 'mentor', 'Todd', '15555550020', '1970-01-01', 'T7–T12', 'T12', 'Complete', null, null, 'Roseville', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/acede200-8379-426d-9c5a-f4d99c787bde/Facetune_20-05-2024-17-21-09.png?format=500w', 'Manual chair; almost full upper body function. Lives with his wife and child.', null, array['English']::text[], 'Completely independent', 'Full time', 'Urology and rehab (30 years)', 'College educated', 'Married or partnered', true, array['Ski & snowboard', 'Winter sports', 'Photography']::text[], array['Adaptive sports', 'Sex', 'Infertility', 'Urology and urology products', 'Nutrition', 'Driving']::text[], array['Intermittent catheterization', 'Vehicle modifications']::text[], array['NorCal SCI']::text[], true, true),
  ('ccaae582-c2e5-14f8-a97d-bb501693acd7', 'peer', 'Vicki', '15555550021', '1953-01-01', 'C5–C8', 'C5/6', 'Incomplete', null, null, 'Eureka', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/d2cf5730-9e60-484d-8fc7-3030b0ded91e/Vicki+Butler.jpeg?format=500w', 'Power chair; hand and arm function, no grip, no leg function. Retired; lives with her husband, married 40 years.', null, array['English']::text[], 'Partially dependent', 'Retired', 'State road maintenance; safety officer', 'High school graduate, some college', 'Married or partnered', null, array['Gardening', 'Quilting', 'Weaving']::text[], array['Adaptive equipment', 'Suprapubic tube', 'Colostomy', 'Osteoporosis']::text[], array['Suprapubic catheter', 'Colostomy']::text[], array['NorCal SCI']::text[], false, true),
  ('9c66fd75-0c36-cdbb-880a-e52b5ae6b75b', 'peer', 'Victor', '15555550022', '1991-01-01', 'T1–T6', 'T4', 'Complete', null, null, 'Sunnyvale', 'CA', 'https://images.squarespace-cdn.com/content/v1/639f51bcb6f2d126acbc35ab/387c5cb2-c4a4-4fb4-b15a-97e0ae0cf498/Victor+Esparanza.jpg?format=500w', 'Manual chair. Good arm and hand movement; no feeling below the injury. Single, lives with his auntie; very close family.', null, array['English']::text[], 'Mostly independent', 'Not currently working', 'Construction and flooring (pre-injury)', 'High school graduate', null, null, array['Fitness & exercise', 'Climbing', 'Team sports']::text[], array['Pressure sores', 'Working out', 'Pain management', 'Exercises', 'Self-catheterization', 'Depression', 'Transfers', 'Dressing', 'Paratransit']::text[], array['Intermittent catheterization']::text[], array['NorCal SCI']::text[], false, true)
on conflict (id) do nothing;
